# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for API project
      run: dotnet restore ./CryptoTransactionService.API.csproj

    - name: Build API project
      run: dotnet build ./CryptoTransactionService.API.csproj --configuration Release --no-restore

    - name: Restore dependencies for Test project
      run: dotnet restore ./CryptoTransactionService.TEST.csproj

    - name: Build Test project
      run: dotnet build ./CryptoTransactionService.TEST.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ./CryptoTransactionService.TEST.csproj --no-build --verbosity normal
